[buid]
  functions = "next-automatic-functions"
  publish = "out"

[[redirects]]
  from = "/studio*"
  to = "/studio"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_404"
  status = 404